export const CHANGE_DISPLAY_MODE = 'CHANGE_DISPLAY_MODE';
export const FETCH_SENSORS = 'FETCH_SENSORS';
export const FETCH_SENSORS_SUCCESS = 'FETCH_SENSORS_SUCCESS';
export const FETCH_SENSORS_ERROR = 'FETCH_SENSORS_ERROR';
export const SHOW_FORM = 'SHOW_FORM';
export const HIDE_FORM = 'HIDE_FORM';
export const SET_FORM = 'SET_FORM';